### ISSUE TITLE
Urgent: Pay Pal failures

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#563] opened 2017-08-06 03:39 UTC
Customer tried to purchase goods for Marin Humane and HSTT via pay pal and it failed. Linda McMahon, maclin@earthlink.net

**Comment by DeveloperRegistry** [comment] 2017-08-06 17:24
Fixed by Dima. The issue is related to mismatches between individual items total and our total calculation due to rounding. The issue is fixed.

**Closed as completed by DeveloperRegistry** 2017-08-06 17:24 UTC
Labels: bug
