### ISSUE TITLE
Wishlist bug

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#379] opened 2014-11-02 21:39 UTC
There is strange images of items right below the actual list of goods (in mobile version only)
![screen shot 2014-11-02 at 1 35 39 pm](https://cloud.githubusercontent.com/assets/4335901/4876968/4765bbee-62d8-11e4-903b-19ce6162c80b.png)

**Comment by DeveloperRegistry** [comment] 2014-11-02 22:00
These images were put there to accommodate Mobile Design. They will be used for display on mobile devices. The original  Goods Items will be hidden by the front end developer. Essentially, what you observe if the work in progress. Extra images will be hidden within 1-2 days when we deploy Mobile changes for Wishlists.

**Comment by DeveloperRegistry** [comment] 2014-11-11 11:30
Closing as not a bug

**Closed as completed by DeveloperRegistry** 2014-11-11 11:30 UTC
Labels: bug
